// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// starmaCPP
Rcpp::List starmaCPP(const arma::mat& data, const Rcpp::List& wlist, arma::mat arMat, arma::mat maMat, int iterate);
RcppExport SEXP starma_starmaCPP(SEXP dataSEXP, SEXP wlistSEXP, SEXP arMatSEXP, SEXP maMatSEXP, SEXP iterateSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist(wlistSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type arMat(arMatSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type maMat(maMatSEXP);
    Rcpp::traits::input_parameter< int >::type iterate(iterateSEXP);
    __result = Rcpp::wrap(starmaCPP(data, wlist, arMat, maMat, iterate));
    return __result;
END_RCPP
}
// stcovCPP
double stcovCPP(const arma::mat& data, const Rcpp::List& wlist, int slag1, int slag2, int tlag);
RcppExport SEXP starma_stcovCPP(SEXP dataSEXP, SEXP wlistSEXP, SEXP slag1SEXP, SEXP slag2SEXP, SEXP tlagSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist(wlistSEXP);
    Rcpp::traits::input_parameter< int >::type slag1(slag1SEXP);
    Rcpp::traits::input_parameter< int >::type slag2(slag2SEXP);
    Rcpp::traits::input_parameter< int >::type tlag(tlagSEXP);
    __result = Rcpp::wrap(stcovCPP(data, wlist, slag1, slag2, tlag));
    return __result;
END_RCPP
}
// stacfCPP
arma::mat stacfCPP(const arma::mat& data, const Rcpp::List& wlist, int tlagMax);
RcppExport SEXP starma_stacfCPP(SEXP dataSEXP, SEXP wlistSEXP, SEXP tlagMaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist(wlistSEXP);
    Rcpp::traits::input_parameter< int >::type tlagMax(tlagMaxSEXP);
    __result = Rcpp::wrap(stacfCPP(data, wlist, tlagMax));
    return __result;
END_RCPP
}
// stpacfCPP
arma::mat stpacfCPP(const arma::mat& data, const Rcpp::List& wlist, int tlagMax);
RcppExport SEXP starma_stpacfCPP(SEXP dataSEXP, SEXP wlistSEXP, SEXP tlagMaxSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< const arma::mat& >::type data(dataSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type wlist(wlistSEXP);
    Rcpp::traits::input_parameter< int >::type tlagMax(tlagMaxSEXP);
    __result = Rcpp::wrap(stpacfCPP(data, wlist, tlagMax));
    return __result;
END_RCPP
}
